### PR TITLE
Add values.schema.json to EFK

### PR DESCRIPTION
**Pull request by cokiengchiara**
Towards https://github.com/giantswarm/roadmap/issues/136

This PR adds `values.schema.json` generated from the current values.yaml using https://github.com/karuppiah7890/helm-schema-gen

It is a good starting point and can be further refined by those that know more about the specifics of the values. (For example if we know that `provider` must be aws|azure|kvm, we can actually enforce that as well using the 'enum' property: https://json-schema.org/understanding-json-schema/reference/generic.html#enumerated-values)

Here's also some more general info: https://www.arthurkoziel.com/validate-helm-chart-values-with-json-schemas/

I validated this generated schema against `efk-stack-app` values currently deployed in

- rfjh2 in gorilla
- 03czy in puma
- z74gp in orion

and they all passed with no errors.

I used the currently in progress `kubectl-gs validate apps` command to help with the verifying current values : https://github.com/giantswarm/kubectl-gs/pull/196

Here's also a slack thread with a video about how that command works: https://gigantic.slack.com/archives/CRZN9GLJW/p1603092812002400

I don't actually know what someone should check or do to approve this PR 😂   WDYT - @oponder ? @piontec

### CODE REVIEW

**Review by piontec — COMMENTED** [review]
:tada: Pefect! Nice work!
One change though: please remove that crappy `.DS_Store` macs create I-have-no-idea-why, but they should not be in the repo. Otherwise - LGTM!

**Comment by oponder** [comment]
Looks good to me too! Indeed that .DS_Store file should be deleted though!

PRO TIP: You can tell git to never include .DS_Store's by configuring a global gitignore file: https://coderwall.com/p/vz6ymw/how-to-globally-gitignore-ds_store

My file looks a bit more aggressive than the example they gave though

This is my file that I called `.gitignore_global` and saved in my home folder (AKA `~/`, AKA `/Users/oponder`) : 
```
.DS_Store
._.DS_Store
**/.DS_Store
**/._.DS_Store
```

And then told git to use: `git config --global core.excludesfile ~/.gitignore_global`

**Comment by oponder** [comment]
Oh also the linter wants a newline at the end of Chart.yaml: https://app.circleci.com/jobs/github/giantswarm/efk-stack-app/175

**Comment by cokiengchiara** [comment]
OK! Deleted the DS store file and added new line!

**Review by piontec — COMMENTED** [review]
LGTM

**Pull request merged**
