### PR TITLE
Move Monitoring Annotation to Label

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR:

- adds/changes/removes etc

### Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by webwurst** [comment]
Why is this needed? :) Just curious.

**Comment by QuentinBisson** [comment]
The annotation was used by g8s-prometheus but he new setup is using the label as service monitors can only use labels as they are indexed by Kubernetes

**Comment by webwurst** [comment]
After these changes only `elasticsearch-exporter` has that label. Is that intended?

**Comment by QuentinBisson** [comment]
The label is already set on the other components so I only had to remove the annotation from them

**Comment by webwurst** [comment]
Should it be set over there? https://github.com/giantswarm/efk-stack-app/blob/fbdd0b3f0bb060811c337cd05fe99b74c68496eb/helm/efk-stack-app/charts/fluentd-elasticsearch/values.yaml#L202

**Comment by QuentinBisson** [comment]
Theoretically, yes, but we cannot get servicemonitor from workload clusters yet

**Review by webwurst — APPROVED** [review]

**Pull request merged**
